spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    url: jdbc:mysql://localhost:3306/springPlus
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  application:
    name: springPlus
  cloud:
    aws:
      s3:
        bucket: springplus-profile-image-bucket
      region:
        static: ap-southeast-2
jwt:
  secret:
    key: ${JWT_SECRET_KEY}