spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    url: ${RDS_URL}/springPlus
    password: ${RDS_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  application:
    name: springPlus
jwt:
  secret:
    key: ${JWT_SECRET_KEY}